CONFIG_ZBOOK_WRAPPER_LUA=y
CONFIG_LUA=y

CONFIG_SERIAL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y

# Sample has no need for a filesystem; the board default pulls in the
# fatfs vendor sources, which this workspace hasn't fetched.
CONFIG_FAT_FILESYSTEM_ELM=n

CONFIG_BOOT_BANNER=n
CONFIG_LOG=y
CONFIG_LUA_ZEPHYR_LOG_LEVEL_DBG=y

CONFIG_SEMIHOST=y
CONFIG_LOG_BACKEND_SEMIHOST=y
CONFIG_LOG_PRINTK=y

CONFIG_ASSERT=y
CONFIG_MAIN_STACK_SIZE=4096

CONFIG_SYS_HEAP_RUNTIME_STATS=y
CONFIG_INIT_STACKS=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_SYS_HEAP_ARRAY_SIZE=1
CONFIG_THREAD_NAME=y
